# Generated by Django 4.2.16 on 2024-11-24 13:26

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(max_length=100)),
                ('user', models.TextField(default=django.contrib.auth.models.User)),
            ],
        ),
    ]
