# Generated by Django 4.2.16 on 2024-11-24 13:49

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user', models.TextField(default=django.contrib.auth.models.User)),
                ('title', models.TextField(max_length=100)),
                ('front', models.TextField(max_length=100)),
                ('back', models.TextField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardApp.project')),
            ],
        ),
    ]
