# Generated by Django 4.2.16 on 2024-11-25 10:18

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardApp.project'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.IntegerField(default=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.IntegerField(default=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='user',
            field=models.IntegerField(default=django.contrib.auth.models.User),
        ),
    ]
