# Generated by Django 4.2.16 on 2024-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0004_alter_card_project_alter_card_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='user',
            field=models.TextField(max_length=100),
        ),
    ]
