# Generated by Django 4.2.16 on 2024-11-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0005_alter_card_user_alter_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='backtext',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fronttext',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.FileField(null=True, upload_to='Cards/back/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.FileField(null=True, upload_to='Cards/front/'),
        ),
    ]
