# Generated by Django 4.2.16 on 2024-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0006_card_backtext_card_fronttext_alter_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.ImageField(null=True, upload_to='Cards/back/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.ImageField(null=True, upload_to='Cards/front/'),
        ),
    ]
