# Generated by Django 4.2.16 on 2024-12-02 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0007_alter_card_back_alter_card_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardChars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('front', models.ImageField(null=True, upload_to='Cards/front/')),
                ('back', models.ImageField(null=True, upload_to='Cards/back/')),
                ('fronttext', models.CharField(max_length=100, null=True)),
                ('backtext', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardApp.project')),
            ],
        ),
    ]
