# Generated by Django 4.2.16 on 2024-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date_created',
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
