# Generated by Django 4.2.16 on 2024-12-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_income_date_created_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='tax',
            field=models.BooleanField(default=False),
        ),
    ]
